### ISSUE TITLE
Custom drawable element

### ISSUE THREAD

**Issue by darmie** [viridia/quill_v1#24]
Well done on this project, I am loving it so far. 

I am building an editor, and I want to render a flow graph within a quill UI element. I could create the nodes using quill, but the connectors between the nodes would need to be drawn as a bezier curve.  Something similar to the image below

![image](https://github.com/viridia/quill/assets/848002/d6eba084-68c8-4050-82e6-24976e373eb4)

I learned that I could use 2D gizmos for immediate mode drawing, but I am new to Bevy and Quill and I don't know how to create a "canvas" for the bevy [gizmos](https://bevyengine.org/examples/2D%20Rendering/2d-gizmos/) that is clipped to a Quill UI view.

Please note that I already have a view inset for the 3D world and camera. 

## Here's what my UI looks like
<img width="1512" alt="Screenshot 2024-05-11 at 20 32 10" src="https://github.com/viridia/quill/assets/848002/f41a063a-77fa-43a0-bcde-d315d7e8dcf6">

**Comment by viridia** [comment]
This project is no longer active, and has been superseded by bevy_reactor. The latter includes a widget that is able to draw a spline curve using SDFs in a custom shader. Note that neither Quill nor bevy_reactor have an official release however.

**Comment by darmie** [comment]
Oh wow. I'll take a look at `bevy_reactor` then.
